[project]
name = "100-days-of-grind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckduckgo-search>=7.3.2",
    "jupyter>=1.1.1",
    "langchain-community>=0.3.17",
    "langchain-ollama>=0.2.3",
    "langgraph>=0.2.70",
    "torch>=2.6.0",
]
